- name: "topic: CI/CD"
  color: "54f449"
  description: "This issue/PR relates to CI/CD pipeline change"
- name: "topic: code style"
  color: "54f449"
  description: "This issue/PR relates to code style."
  from_name: "code quality"
- name: "topic: tests"
  color: "54f449"
  description: "This issue/PR relates to tests, QA, CI."
- name: "topic: deprecated"
  color: "999999"
  description: "Feature or component marked as deprecated and will be removed"
- name: "topic: documentation"
  color: "54f449"
  description: "This issue/PR relates to or includes documentation."
  from_name: "Documentation"
- name: "type: breaking-change"
  color: "310372"
  description: "Marks an important and likely breaking old interface change."
- name: "type: feature"
  color: "310372"
  description: "New feature implementation"
- name: "type: enhancement"
  color: "310372"
  description: "Enhancement update for old feature"
  from_name: "enhancement"
- name: "type: good first issue"
  color: "310372"
  description: "Good for newcomers"
  from_name: "Good first contrib"
- name: "type: bug"
  color: "b71914"
  description: "Something isn't working"
  from_name: "bug"
- name: "log:added"
  color: "ff935e"
  description: "Changelog mark label. Marks new added features."
- name: "log:breaking-change"
  color: "ff935e"
  description: "Changelog mark label. Marks breaking changes."
- name: "log:changed"
  color: "ff935e"
  description: "Changelog mark label. Marks old, but changed features."
- name: "log:deprecated"
  color: "ff935e"
  description: "Changelog mark label. Marks deprecated features, that will be removed in next major release."
- name: "log:fixed"
  color: "ff935e"
  description: "Changelog mark label. Marks fixed bug issues."
- name: "log:removed"
  color: "ff935e"
  description: "Changelog mark label. Marks removed features."
- name: "log:skip-changelog"
  color: "ff935e"
  description: "Should be excluded from the changelog."
- name: "os: linux"
  color: "fbca04"
  description: "This issue/PR related to linux systems"
- name: "os: mac"
  color: "fbca04"
  description: "This issue/PR related to mac systems"
- name: "os: windows"
  color: "fbca04"
  description: "This issue/PR related to windows systems"
- name: "question"
  color: "d876e3"
  description: "User questions, not related to issues"
  from_name: "question"
- name: "decision: duplicate"
  color: "eeeeee"
  description: "This issue or pull request already exists"
  from_name: "duplicate"
- name: "decision: wontfix"
  color: "eeeeee"
  description: "This will not be worked on"
  from_name: "wontfix"
- name: "decision: wontmerge"
  color: "eeeeee"
  description: "PR Only: This pull request will not be merged (problem described in comments)"
- name: "stage: waiting-for-contributor"
  color: "efc1ae"
  from_name: "awaiting response"
  description: "Waiting for answer from original contributor."
- name: "stage: WIP"
  color: "efc1ae"
  description: "Work In Progress"
- name: "stage: help wanted"
  color: "efc1ae"
  description: "Extra attention is needed"
  from_name: "Help wanted"
