ignore: []

refactor:
  include: []
  skip:
    - use-contextlib-suppress
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.8'

metrics:
  quality_threshold: 25.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false
